BF-FrontEnd-class/agile-development-group1-loruki-rebild

.cspell.json, README.md
=> Add Project-definition

planning/constraints.md
=> add constrainrs

planning/development-strategy.md
=> add development-strategy.md

.vscode/settings.json, index.html, styles/something.css
=> 01 title home

features.html, index.html
=> add-navbar-home

index.html
=> add 02-description-home

styles/something.css
=> add-nav-top-home-css

styles/something.css, styles/utilities.css
=>  added 02-origin/02-description-home:CSS

styles/something.css
=> updated default css settings

.hintrc, .vscode/settings.json, index.html, styles/something.css
=> 08 more information home

index.html, styles/something.css, styles/utilities.css
=> 06 statistics home

features.html
=> Add titile to feature page

index.html, styles/something.css, styles/utilities.css
=> Add 10-footer-copyright-home

index.html, styles/something.css
=> Add 12 Social media home

features.html, styles/utilities.css
=> Add 17 More info

index.html, styles/something.css
=> 09 -supported -languages

features.html, planning/docs.html
=> add left navigation bar on docs page

features.html, index.html
=> add 21-footer-nav-features:HTML

planning/retrospective.md
=> Add retrospective

pages/docs.html
=> add 33-footer-social-docs:HTML

pages/features.html, styles/something.css
=> add 22-social-media-features:HTML

index.html
=> delete repeated Sign form

styles/something.css, styles/utilities.css
=> add 04-sign-in-form:CSS

pages/features.html
=> fix links to styles & fix links to pages

pages/docs.html
=> added navbar to the footer docs.html

styles/something.css, styles/utilities.css
=> added flex & container to the css files

pages/docs.html
=> added navbar to docs.html

pages/docs.html
=> added installation guid to docs.html

pages/docs.html
=> added copyright mark to docs.html

index.html
=> added sign form to index

pages/docs.html
=> added intro to docs

pages/docs.html
=> added title to docs

pages/docs.html, styles/index.css
=> udate links

pages/docs.html
=> check docs.html

pages/features.html
=> check features.html

styles/something.css
=> check somethings.css

index.html
=> check index.html

styles/utilities.css
=> check utilities.css

planning/user-personas.md
=> update links to photo
